//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    using WpfApp1.Interfaces;

    public partial class ProductMaterial : Notify
    {
        public int ProductID { get; set; }
        public int MaterialID { get; set; }
        private Nullable<double> _count;
        public Nullable<double> Count { get => _count; set { _count = value; OnPropertyChanged(nameof(Product)); } }
    
        public virtual Material Material { get; set; }
        private Product _product;
        public virtual Product Product { get => _product; set { _product = value; OnPropertyChanged(); } }
    }
}
